# Generated by Django 2.1.7 on 2019-05-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('codigoBarras', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=7)),
                ('unidades', models.IntegerField(default=0)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=2)),
                ('nombre', models.CharField(max_length=15)),
                ('categoria', models.CharField(max_length=15)),
            ],
        ),
    ]
